apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: mirth-connect-scc
allowPrivilegedContainer: false
allowPrivilegeEscalation: false
requiredDropCapabilities:
  - ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - "runtime/default"
readOnlyRootFilesystem: false
users: []
groups: []